/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'all_ops_m0plus.Release+T2G-Kit' 
 * Target:  'Release+T2G-Kit' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.4.0-stage */
/* ExecuTorch global configuration */
        #define C10_USING_CUSTOM_GENERATED_MACROS
        #define FLATBUFFERS_MAX_ALIGNMENT 1024
        #define FLATBUFFERS_LOCALE_INDEPENDENT 0


#endif /* PRE_INCLUDE_GLOBAL_H */
